# -*- coding: utf-8 -*-
"""cv_lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY2S4RgH110qMrfqVOTQUNW7zmnSEZz_
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparison(original,sobel,prewitt,canny):
    plt.figure(figsize=(12,10))
    plt.subplot(2,2,1)
    plt.imshow(original,cmap='gray')
    plt.title("original grayscale image")
    plt.axis('off')
    plt.subplot(2,2,2)
    plt.imshow(sobel,cmap='gray')
    plt.title("sobel edge detection")
    plt.axis('off')
    plt.subplot(2,2,3)
    plt.imshow(prewitt,cmap='gray')
    plt.title("prewitt edge detection")
    plt.axis('off')
    plt.subplot(2,2,4)
    plt.imshow(canny,cmap='gray')
    plt.title("canny edge detection")
    plt.axis('off')
    plt.tight_layout()
    plt.show()

img=cv2.imread('/content/batman.jpg')
if img is None:
  print("error:image not found")
else:
    # Convert image to grayscale for edge detection
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Prewitt filter
    kernelx=np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
    kernely=np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    prewittx=cv2.filter2D(gray_img,-1,kernelx)
    prewitty=cv2.filter2D(gray_img,-1,kernely)
    prewitty_combined=np.uint8(np.absolute(prewittx) + np.absolute(prewitty))

    # Sobel filter
    sobel_x = cv2.Sobel(gray_img, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(gray_img, cv2.CV_64F, 0, 1, ksize=3)
    sobel_combined = np.uint8(np.absolute(sobel_x) + np.absolute(sobel_y))

    # Canny edge detection
    canny_edges=cv2.Canny(gray_img,100,200)

    show_comparison(img,sobel_combined,
                    prewitty_combined,canny_edges)